/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-has-hM1N5ieh2GVxcpRo8IB-PWc35YJM5o383jsnpPVOjNMwPkwiIMS3-WsehyXmzevVBlGySRhXRLcOdlgBgCCqIrt-7guuroBVskz0dVjAmMHFWag65zMO",
  "tt": "tt-1-oVdOn9dM-nzqp-LOggzSoDWrhe46aL8G7AETSxJ5Jo4=",
  "version": "2020-11-20"
}

export default ebconfig;